// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[slug]/index.tsx";
import * as $1 from "./routes/[slug]/vote.tsx";
import * as $2 from "./routes/_404.tsx";
import * as $3 from "./routes/_500.tsx";
import * as $4 from "./routes/_app.tsx";
import * as $5 from "./routes/_middleware.tsx";
import * as $6 from "./routes/admin/_middleware.tsx";
import * as $7 from "./routes/admin/choices/[slug]/delete.tsx";
import * as $8 from "./routes/admin/choices/[slug]/edit.tsx";
import * as $9 from "./routes/admin/choices/[slug]/index.tsx";
import * as $10 from "./routes/admin/choices/index.tsx";
import * as $11 from "./routes/admin/choices/new.tsx";
import * as $12 from "./routes/admin/groups/[slug]/delete.tsx";
import * as $13 from "./routes/admin/groups/[slug]/edit.tsx";
import * as $14 from "./routes/admin/groups/[slug]/index.tsx";
import * as $15 from "./routes/admin/groups/index.tsx";
import * as $16 from "./routes/admin/groups/new.tsx";
import * as $17 from "./routes/admin/index.tsx";
import * as $18 from "./routes/admin/polls/[slug]/delete.tsx";
import * as $19 from "./routes/admin/polls/[slug]/edit.tsx";
import * as $20 from "./routes/admin/polls/[slug]/index.tsx";
import * as $21 from "./routes/admin/polls/index.tsx";
import * as $22 from "./routes/admin/polls/new.tsx";
import * as $23 from "./routes/all.tsx";
import * as $24 from "./routes/api/polls/[id].ts";
import * as $25 from "./routes/auth/callback.ts";
import * as $26 from "./routes/auth/google.tsx";
import * as $27 from "./routes/auth/index.tsx";
import * as $28 from "./routes/auth/signin.ts";
import * as $29 from "./routes/auth/signout.ts";
import * as $30 from "./routes/groups/[slug].tsx";
import * as $31 from "./routes/groups/index.tsx";
import * as $32 from "./routes/index.tsx";
import * as $33 from "./routes/me/delete.tsx";
import * as $34 from "./routes/me/download.ts";
import * as $35 from "./routes/me/index.tsx";
import * as $36 from "./routes/privacy-policy.tsx";
import * as $37 from "./routes/validate-account.ts";
import * as $$0 from "./islands/ChoicesTableBodyIsland.tsx";

const manifest = {
  routes: {
    "./routes/[slug]/index.tsx": $0,
    "./routes/[slug]/vote.tsx": $1,
    "./routes/_404.tsx": $2,
    "./routes/_500.tsx": $3,
    "./routes/_app.tsx": $4,
    "./routes/_middleware.tsx": $5,
    "./routes/admin/_middleware.tsx": $6,
    "./routes/admin/choices/[slug]/delete.tsx": $7,
    "./routes/admin/choices/[slug]/edit.tsx": $8,
    "./routes/admin/choices/[slug]/index.tsx": $9,
    "./routes/admin/choices/index.tsx": $10,
    "./routes/admin/choices/new.tsx": $11,
    "./routes/admin/groups/[slug]/delete.tsx": $12,
    "./routes/admin/groups/[slug]/edit.tsx": $13,
    "./routes/admin/groups/[slug]/index.tsx": $14,
    "./routes/admin/groups/index.tsx": $15,
    "./routes/admin/groups/new.tsx": $16,
    "./routes/admin/index.tsx": $17,
    "./routes/admin/polls/[slug]/delete.tsx": $18,
    "./routes/admin/polls/[slug]/edit.tsx": $19,
    "./routes/admin/polls/[slug]/index.tsx": $20,
    "./routes/admin/polls/index.tsx": $21,
    "./routes/admin/polls/new.tsx": $22,
    "./routes/all.tsx": $23,
    "./routes/api/polls/[id].ts": $24,
    "./routes/auth/callback.ts": $25,
    "./routes/auth/google.tsx": $26,
    "./routes/auth/index.tsx": $27,
    "./routes/auth/signin.ts": $28,
    "./routes/auth/signout.ts": $29,
    "./routes/groups/[slug].tsx": $30,
    "./routes/groups/index.tsx": $31,
    "./routes/index.tsx": $32,
    "./routes/me/delete.tsx": $33,
    "./routes/me/download.ts": $34,
    "./routes/me/index.tsx": $35,
    "./routes/privacy-policy.tsx": $36,
    "./routes/validate-account.ts": $37,
  },
  islands: {
    "./islands/ChoicesTableBodyIsland.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
